name: Scrape Nautilus Updates

on:
  schedule:
    - cron: '*/30 * * * *'  # runs every 30 min in UTC :contentReference[oaicite:9]{index=9}
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run scraper
        run: python scrape_nautilus.py
      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last.txt updates.json
          git diff --quiet || (git commit -m "Log update: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" && git push)
